// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ2Cs1Q-xD2LYAZnjhGM9UkM2aq7lBx14',
    appId: '1:362141200844:web:5541f6854ff19e5578ad69',
    messagingSenderId: '362141200844',
    projectId: 'ice-cream-7deb3',
    authDomain: 'ice-cream-7deb3.firebaseapp.com',
    storageBucket: 'ice-cream-7deb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8WDxKYhJEupglIvYoCfTuh-VvPQ6mE0',
    appId: '1:362141200844:android:5902be1d21e4285778ad69',
    messagingSenderId: '362141200844',
    projectId: 'ice-cream-7deb3',
    storageBucket: 'ice-cream-7deb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHL6KzuJYSMcuXDedh4dFZl8ehJB3q_F4',
    appId: '1:362141200844:ios:d427543da7da2f2778ad69',
    messagingSenderId: '362141200844',
    projectId: 'ice-cream-7deb3',
    storageBucket: 'ice-cream-7deb3.appspot.com',
    iosClientId: '362141200844-n6s3vactqg330pdgq9bgk09ugp88nn1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.iccycream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHL6KzuJYSMcuXDedh4dFZl8ehJB3q_F4',
    appId: '1:362141200844:ios:e3a063f8a1f8966c78ad69',
    messagingSenderId: '362141200844',
    projectId: 'ice-cream-7deb3',
    storageBucket: 'ice-cream-7deb3.appspot.com',
    iosClientId: '362141200844-48ddm4nmpft366ai65lb1hrukfq9gsqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.iccycream.RunnerTests',
  );
}
